"""Add resolved_link to Link

Revision ID: 9326df6c209a
Revises: 95a0b2361d0e
Create Date: 2024-06-01 15:40:58.857639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9326df6c209a'
down_revision: Union[str, None] = '95a0b2361d0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('resolved_link', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'resolved_link')
    # ### end Alembic commands ###
